services:
  - type: web
    name: vas-care
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: PHP_VERSION
        value: 8.2.0 