services:
  - type: web
    name: vas-care
    env: php
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT -t public/
    envVars:
      - key: PHP_VERSION
        value: 8.2.0
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /
    autoDeploy: true 