services:
  - type: web
    name: vas-care
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: public
      - key: DB_HOST
        fromDatabase:
          name: vas-care-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: vas-care-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: vas-care-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: vas-care-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: vas-care-db
          property: password

databases:
  - name: vas-care-db
    plan: free 